### PR TITLE
[#102845416] Fix 500s for bad service ids

### PR DESCRIPTION
**Pull request by TheDoubleK**
Should fix this bug: https://www.pivotaltracker.com/story/show/102845416

Most of the fix is in utils - this just pulls utils in and fixes an error message.

Depends on this utils update going in first:
- [x] https://github.com/alphagov/digitalmarketplace-utils/pull/161

### CODE REVIEW

**Comment by robyoung** [comment]
I wonder if importing `unicode_literals` from `__future__` would be more appropriate given that we're not really porting a legacy Python 2 API.

http://python-future.org/unicode_literals.html
https://docs.djangoproject.com/en/1.8/topics/python3/#unicode-literals

**Comment by TheDoubleK** [comment]
That looks like a nice solution. Will do the same for utils too.

**Comment by TheDoubleK** [comment]
Done, but needs the corresponding Utils PR to go in again now.

**Comment by robyoung** [comment]
:+1:

**Pull request merged**
