### PR TITLE
help page: add information about the Public Procurement Review Service

### PR DESCRIPTION
**Pull request by risicle**
https://trello.com/c/xey48L9F

@pocketstefan what do you think about the positioning of this paragraph? Stuck it second to last...

Also I noticed that all the other paragraphs use the form "Email abc@example.com if..." - do you think we should try and fit in with that somehow? Should I make the email address visible instead of just a blind `mailto:` link?

image

### CODE REVIEW

**Comment by pocketstefan** [comment]
@risicle Looks good! yes I agree let's change it to 'Email publicprocurementreview@cabinetoffice.gov.uk if a buyer isn't...'

**Comment by risicle** [comment]
Cool. Is it important that we then wouldn't be using the full name "Public Procurement Review Service" anywhere if we did that?

**Comment by pocketstefan** [comment]
@risicle No, I think just the email is fine.

**Comment by risicle** [comment]
Cool. Changed.

**Comment by risicle** [comment]
Woohoo

**Pull request merged**
