### PR TITLE
Re-adding padding class 

### PR DESCRIPTION
**Pull request by carolinegreen**
Re-adding padding class as dmspeak in its current form does not work foor this page.  Can look at how dmspeak and padding classes should be used later.

### CODE REVIEW

**Comment by TheDoubleK** [comment]
The `dmspeak` class needs to go on the wrapper rather than the individual `p`s, e.g. 
```
<div class="dmspeak">
  <p>Blah...</p>
  <p>Blah...</p>
</div>
```

**Comment by carolinegreen** [comment]
Yes, and then everything is spaced out, so I'll have to change a class that doesn't even have an example.

**Comment by TheDoubleK** [comment]
OK cool :+1:

**Comment by TheDoubleK** [comment]
Merging this as going to release the buyer app now.

**Pull request merged**
