### PR TITLE
Watch for changes to content

### PR DESCRIPTION
**Pull request by quis**
Implements https://github.com/alphagov/digitalmarketplace-utils/pull/193

Adds https://pypi.python.org/pypi/watchdog as a requirement to make watching for file changes use system events, which is faster

### CODE REVIEW

**Comment by quis** [comment]
# Have flask init init the manager
Depends on and implements alphagov/digitalmarketplace-utils#195

**Comment by quis** [comment]
# Bring in 11.1.1 of utils

To allow us to use the version of `init_manager` which returns a `Manager` instance.

**Comment by robyoung** [comment]
Once tests pass :+1:

**Comment by quis** [comment]
@tombye Sorry. Tired. Fixed in 23584d2acb98f2602a48f0ef075a5e3b079bc57e.

**Comment by tombye** [comment]
@quis I did exactly the same thing, the first go at https://github.com/alphagov/digitalmarketplace-supplier-frontend/commit/7db91ecea684598b5264f285a85110f20aa03a00, just had a bit more time to correct it :)

**Pull request merged**
