### PR TITLE
Nora gds cookiechanges 1

### PR DESCRIPTION
**Pull request by NoraGDS**
Updated content. Added new content and table for probe cookie

### CODE REVIEW

**Comment by katstevens** [comment]
Content looks good to me - there is a failing Python unit test though, which is looking for the old `<h1>Cookies</h1>` header. I'll add a commit to fix that. I can also 'squash' your first test commit at the same time if you like?

**Comment by NoraGDS** [comment]
Thank you. Yes please.

**Comment by katstevens** [comment]
Here's a screenshot of how the changes look on my machine:

cookies-page

I think the GOV.UK link needs to be an `<a href="...">` rather than a markdown link. The rest of it looks OK to me, but have a look and see what you think 😸

**Comment by risicle** [comment]
(that's "Looks Good To Me")

**Pull request merged**
