### PR TITLE
Updated footer links for DOS launch

### PR DESCRIPTION
**Pull request by tombye**
https://www.pivotaltracker.com/story/show/117934777

Brings in new pages on www.gov.uk and removes links made redundant by the launch of the Digital
Outcomes and Specialists framework.

### Before

old_footer_links

### After

new_footer_links

Should be merged along with https://github.com/alphagov/digitalmarketplace-supplier-frontend/pull/460

### CODE REVIEW

**Comment by TheDoubleK** [comment]
Are we happy to lose the digital services framework link while it is still live and the only option for buyers? i.e. should we merge this now, or wait until Monday?

**Comment by TheDoubleK** [comment]
Links look good but confirmed by Sarah that we shouldn't merge these until DOS is live.

**Comment by tombye** [comment]
OK, me, Sarah and @superroz went through this and made the three changes above. These replaced the DSF link but also added a few edits to make the links work better. I've updated the screenshot of the new one to the latest version.

**Comment by TheDoubleK** [comment]
Links look good.

Should we also remove all the unlinked pages from the app now?
e.g. `/g-cloud/framework`, ``, `/crown-hosting/framework`, `/buyers-guide`, etc.?

We might never remember otherwise.

We should make them all redirect to the new GOV.UK urls with "301 Moved Permanently" for now.

**Comment by tombye** [comment]
Good idea, I'll get on it.

**Comment by TheDoubleK** [comment]
Or add it to the icebox if you can't be arsed right now :)

**Comment by tombye** [comment]
@TheDoubleK 64772c2 and 0939a77 should include all the work with redirects.

**Comment by TheDoubleK** [comment]
:boom: 
screen shot 2016-04-21 at 15 56 21
 :boom:

:+1:

**Pull request merged**
