### PR TITLE
Show award status on opportunity page

### PR DESCRIPTION
**Pull request by CrystalPea**
For details please see the Trello ticket:
https://trello.com/c/fHudofRp/747-2-show-award-status-on-opportunity-page

awarded-opportunity-screenshot

### CODE REVIEW

**Comment by laurenceberry** [comment]
Looking good, could we display either SME or large? 
Sorry, I should have made this clear in the mockups.

**Comment by CrystalPea** [comment]
@laurenceberry this is done now :). New screenshot will follow tomorrow hopefully!

**Comment by katstevens** [comment]
@laurenceberry New screenshot now added. A quick question about the contract value - above we've truncated the value if it ends in zero pence, i.e. £20,000 rather than £20,000.00. If the pence is non-zero, we still show it (e.g. £20,000.10). Is this OK or should we always show pence?

**Comment by katstevens** [comment]
This branch is blocked by https://github.com/alphagov/digitalmarketplace-buyer-frontend/pull/582

**Pull request merged**
