### PR TITLE
Crown hosting content updates from ccs

### PR DESCRIPTION
**Pull request by superroz**
Removing references to 'legacy systems' and 'services that aren't ready to migrate to the cloud'. Also tidying up a few style things.

### CODE REVIEW

**Comment by superroz** [comment]
@annhelen Can you take a look please?

**Comment by TheDoubleK** [comment]
This looks fine to me.  The link text change will break the functional tests, and I've got a PR here that will fix them, so this should be merged at the same time as this one:
 - [ ] https://github.com/alphagov/digitalmarketplace-functional-tests/pull/266

**Comment by annhelen** [comment]
@superroz all looks fine to me

**Comment by superroz** [comment]
Fab. That's good enough for me. If someone could merge this when the other one's ready that would be super.

**Pull request merged**
