### PR TITLE
Changed url of service page

### PR DESCRIPTION
**Pull request by minglis**
- We refer to services everywhere (API and so on)
- Buyer app page is service (singluar)
- Updated to be services as per other facets of the DM.

### CODE REVIEW

**Comment by robyoung** [comment]
There should be at least one test around this view.

**Comment by quis** [comment]
You'll want to look at this nomenclature [in the admin app](https://github.com/alphagov/digitalmarketplace-admin-frontend/blob/master/app/main/views.py#L53-L89) as well.

**Comment by minglis** [comment]
Tests added ready to go.

**Comment by minglis** [comment]
@quis URLs are interesting - we've plumped for services plural in all the APIs. Was bringing this into line. Note that the grails app is service singular.

We need to do a redirect for all grails URLs if we, as Ash wants, add framework into the urls:

/g-cloud/search
/g-cloud/services
/digital-specialists/search
etc

So we can change from service to services as part of that if we choose to do it.

**Comment by quis** [comment]
@minglis So shouldn't this PR also do the redirect from `/service/…` to `/services/…`?

**Comment by robyoung** [comment]
We have a [`@deprecated`](https://github.com/alphagov/digitalmarketplace-utils/blob/master/dmutils/deprecation.py) decorator in the utils package for monitoring changes like this.

**Comment by TheDoubleK** [comment]
Unless anyone has strong feelings about this I'm tempted to get this merged now - adding the redirects is part of this upcoming story: https://www.pivotaltracker.com/n/projects/997836

**Comment by quis** [comment]
@TheDoubleK What story? That link just goes to the project in Pivotal. LGTM :+1: though if there is a followup to deal with redirects/deprecation.

**Comment by TheDoubleK** [comment]
Sorry - https://www.pivotaltracker.com/story/show/93097694

**Pull request merged**
