### PR TITLE
Overview page styling amends

### PR DESCRIPTION
**Pull request by tombye**
The overview page was styled so its numbers and ticks were positioned outside the main list.

This brings them inside the list to match the prototype.

### Before

overview_old

### After

overview_new

### CODE REVIEW

**Comment by pcraig3** [comment]
[Prototype also has black horizontal lines](http://dm-prototype.herokuapp.com/outcome-overview).

I like grey better personally, but is this a decision we've actually made or a thing we never fixed?

**Comment by pcraig3** [comment]
I think the rest of it looks good though!

**Comment by tombye** [comment]
@pcraig3 I spoke to @ralph-hawkins about this and he said he's ok for us to keep using the `$border-colour` Sass variable (as we do now) for this. We will add a DM-level border variable for the darker look at a later point which can then be brought into this pattern but it'll still be done at the DM toolkit level.

**Comment by pcraig3** [comment]
👍

**Comment by pcraig3** [comment]
thumbs_up

**Pull request merged**
