### PR TITLE
Add latest search patterns from toolkit

### PR DESCRIPTION
**Pull request by quis**
This commit bumps the version of the Digital Marketplace frontend toolkit, which updates the following patterns:
- Search result (now looks more like a GOV.UK finder)
- Multi-select (now renamed to 'option select' and using a more recent version of the GOV.UK component)

image

### CODE REVIEW

**Comment by robyoung** [comment]
If I uncheck boxes and click filter again they remain checked.

**Comment by quis** [comment]
@robyoung Is that something that this PR has broken, or something that's broken already?

**Comment by robyoung** [comment]
I don't know, this is the first time I've started up this app. Do you want me to raise that as a separate bug?

**Comment by quis** [comment]
I don't really know the history of the app… It might well be something that
@tombye is fixing with his forthcoming mega pull request.

**Comment by quis** [comment]
Rebased on top of @tombye's branch, for review as one unit.

**Pull request merged**
