### PR TITLE
Change to homepage copy

### PR DESCRIPTION
**Pull request by quis**
From CCS this morning

image

### CODE REVIEW

**Comment by tombye** [comment]
Do we have to explain what 'BST' means?

**Comment by tombye** [comment]
Talking with @superroz, writing it in full would cause more disruption. We could wrap it in an `<abbr>` tag  to put the information in there though.

**Comment by quis** [comment]
@tombye Good idea. Added in d9fedfdf37b03b47241eff9fe8c1164254790926.

**Comment by superroz** [comment]
Happy to change to British Summer Time (BST) if we think BST isn't well understood. Could we have a full stop after 'in becoming a G-Cloud 7 supplier'?

**Comment by quis** [comment]
@superroz 53204de

**Comment by tombye** [comment]
This is what it would look like if we used the full form:

image

Thoughts?

**Comment by tombye** [comment]
Talking with @quis and @superroz the form as it currently is is most suitable.

:+1:

**Pull request merged**
