### PR TITLE
bumping frameworks version

### PR DESCRIPTION
**Pull request by danielknell**
updating to pull in recent version of frameworks

### CODE REVIEW

**Comment by idavidmcdonald** [comment]
Would be good to include what the version bump you are doing in the commit message, e.g. "Bump frameworks version to x.x.x"

**Comment by pcraig3** [comment]
yeah and also including a version of the framework that david hasn't made an enormous mistake in would be good.

**Comment by idavidmcdonald** [comment]
🔥 🚒 🔥

**Comment by idavidmcdonald** [comment]
Commit message says 5.1.1 but code says 5.1.2

**Comment by idavidmcdonald** [comment]
👍 good when tests pass

**Pull request merged**
