### PR TITLE
Updates to flash message for too many results message

### PR DESCRIPTION
**Pull request by DilwoarH**
Ticket: https://trello.com/c/kZm5L3ho/77-reduce-limit-for-ending-a-search-to-30-from-100

### CODE REVIEW

**Comment by DilwoarH** [comment]
@karlchillmaid:

This is the code `if int(search_count) > END_SEARCH_LIMIT` so effectively would be 30 or more

**Comment by katstevens** [comment]
The unit tests will need fixing too, once the content has been agreed.

**Comment by karlchillmaid** [comment]
`Refine your search terms until you have no more than 30 results.`

**Comment by DilwoarH** [comment]
@katstevens - tests are now fixed

**Pull request merged**
