### PR TITLE
Adds app-break-link class

### PR DESCRIPTION
**Pull request by domoscargin**
https://trello.com/c/bcU2s0Zs/33-2-links-in-summary-tables-eg-dos-opportunities-dont-wrap-in-safari-or-chrome

The `.break-link` class was previously deleted, resulting in long URLs not getting wrapped.

* Adds `.app-break-link` class styles
* Updates dm-utils version, which adds the class name

### CODE REVIEW

**Comment by lfdebrux** [comment]
Can we rename this to `.app-break-link`?

**Comment by domoscargin** [comment]
> Can we rename this to `.app-break-link`?

We can, but would need to release [this change](https://github.com/alphagov/digitalmarketplace-utils/pull/561) first.

**Comment by lfdebrux** [comment]
This fixes #1014

**Comment by lfdebrux** [comment]
I've tested this locally and it does the job!

**Pull request merged**
